/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) impl_jac_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
#ifndef CASADI_SYMBOL_EXPORT
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#if defined(STATIC_LINKED)
#define CASADI_SYMBOL_EXPORT
#else /* defined(STATIC_LINKED) */
#define CASADI_SYMBOL_EXPORT __declspec(dllexport)
#endif /* defined(STATIC_LINKED) */
#elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
#else /* defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__) */
#define CASADI_SYMBOL_EXPORT
#endif /* defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__) */
#endif /* CASADI_SYMBOL_EXPORT */
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[8] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[5] = {1, 1, 0, 1, 0};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[21] = {4, 8, 0, 0, 2, 3, 6, 7, 8, 9, 10, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
#define s2 CASADI_PREFIX(s2)
/* impl_jacFun */
CASADI_SYMBOL_EXPORT int impl_jacFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][1] : 0;
  real_t a1=cos(a0);
  real_t a2=-8.0000000000000016e-02;
  a1=(a2*a1);
  real_t a3=arg[0] ? arg[0][3] : 0;
  real_t a4=sq(a3);
  a1=(a4*a1);
  real_t a5=cos(a0);
  real_t a6=9.8100000000000009e-01;
  a5=(a6*a5);
  real_t a7=cos(a0);
  a7=(a5*a7);
  real_t a8=sin(a0);
  a8=(a6*a8);
  real_t a9=sin(a0);
  a8=(a9*a8);
  a7=(a7-a8);
  a1=(a1+a7);
  a7=cos(a0);
  a8=sq(a7);
  real_t a10=1.0000000000000001e-01;
  a8=(a10*a8);
  real_t a11=1.1000000000000001e+00;
  a8=(a11-a8);
  a1=(a1/a8);
  real_t a12=sin(a0);
  a12=(a2*a12);
  a4=(a12*a4);
  real_t a13=arg[2] ? arg[2][0] : 0;
  a4=(a4+a13);
  a5=(a5*a9);
  a4=(a4+a5);
  a4=(a4/a8);
  a4=(a4/a8);
  a7=(a7+a7);
  a5=sin(a0);
  a7=(a7*a5);
  a7=(a10*a7);
  a4=(a4*a7);
  a1=(a1-a4);
  a1=(-a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=cos(a0);
  a1=(a2*a1);
  a4=cos(a0);
  a4=(a1*a4);
  a7=sin(a0);
  a2=(a2*a7);
  a7=sin(a0);
  a2=(a7*a2);
  a4=(a4-a2);
  a2=sq(a3);
  a4=(a2*a4);
  a5=sin(a0);
  a5=(a13*a5);
  a4=(a4-a5);
  a5=cos(a0);
  a5=(a6*a5);
  a4=(a4+a5);
  a5=cos(a0);
  a9=9.8100000000000005e+00;
  a5=(a9*a5);
  a4=(a4+a5);
  a5=cos(a0);
  real_t a14=sq(a5);
  a14=(a10*a14);
  a11=(a11-a14);
  a14=8.0000000000000004e-01;
  a11=(a14*a11);
  a4=(a4/a11);
  a1=(a1*a7);
  a2=(a1*a2);
  a7=cos(a0);
  a13=(a13*a7);
  a2=(a2+a13);
  a13=sin(a0);
  a6=(a6*a13);
  a2=(a2+a6);
  a6=sin(a0);
  a9=(a9*a6);
  a2=(a2+a9);
  a2=(a2/a11);
  a2=(a2/a11);
  a5=(a5+a5);
  a0=sin(a0);
  a5=(a5*a0);
  a10=(a10*a5);
  a14=(a14*a10);
  a2=(a2*a14);
  a4=(a4-a2);
  a4=(-a4);
  if (res[0]!=0) res[0][1]=a4;
  a4=-1.;
  if (res[0]!=0) res[0][2]=a4;
  if (res[0]!=0) res[0][3]=a4;
  a4=(a3+a3);
  a12=(a12*a4);
  a12=(a12/a8);
  a12=(-a12);
  if (res[0]!=0) res[0][4]=a12;
  a3=(a3+a3);
  a1=(a1*a3);
  a1=(a1/a11);
  a1=(-a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=1.;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a1;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jacFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jacFun_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jacFun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int impl_jacFun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jacFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jacFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jacFun_sparsity_in(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s0;
    case 2: return s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jacFun_sparsity_out(int i) {
  switch (i) {
    case 0: return s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jacFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 15;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
