/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) impl_jac_x_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[6] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
#define s2 CASADI_PREFIX(s2)
/* impl_jacFun_x */
int impl_jacFun_x(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  if (res[0]!=0) res[0][6]=a0;
  if (res[0]!=0) res[0][7]=a0;
  real_t a1=-1.;
  if (res[0]!=0) res[0][8]=a1;
  real_t a2=7.8182378879940387e+01;
  if (res[0]!=0) res[0][9]=a2;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a0;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a0;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  if (res[0]!=0) res[0][18]=a0;
  if (res[0]!=0) res[0][19]=a0;
  if (res[0]!=0) res[0][20]=a0;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a0;
  a2=4.7418203070092001e-02;
  real_t a3=arg[2] ? arg[2][0] : 0;
  a2=(a2*a3);
  a3=arg[0] ? arg[0][6] : 0;
  real_t a4=cos(a3);
  a4=(a2*a4);
  real_t a5=sin(a3);
  real_t a6=9.8100000000000005e+00;
  a5=(a6*a5);
  a4=(a4+a5);
  a5=2.;
  real_t a7=arg[0] ? arg[0][3] : 0;
  a7=(a5*a7);
  real_t a8=arg[0] ? arg[0][7] : 0;
  real_t a9=(a7*a8);
  a4=(a4+a9);
  a9=arg[0] ? arg[0][2] : 0;
  a4=(a4/a9);
  a4=(a4/a9);
  a4=(-a4);
  if (res[0]!=0) res[0][23]=a4;
  if (res[0]!=0) res[0][24]=a0;
  if (res[0]!=0) res[0][25]=a0;
  if (res[0]!=0) res[0][26]=a1;
  a4=4.0493711676434543e+01;
  if (res[0]!=0) res[0][27]=a4;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a0;
  if (res[0]!=0) res[0][30]=a0;
  a5=(a5*a8);
  a5=(a5/a9);
  if (res[0]!=0) res[0][31]=a5;
  if (res[0]!=0) res[0][32]=a0;
  a5=-3.7072679182318851e+00;
  if (res[0]!=0) res[0][33]=a5;
  if (res[0]!=0) res[0][34]=a0;
  if (res[0]!=0) res[0][35]=a0;
  if (res[0]!=0) res[0][36]=a0;
  if (res[0]!=0) res[0][37]=a0;
  if (res[0]!=0) res[0][38]=a0;
  if (res[0]!=0) res[0][39]=a0;
  if (res[0]!=0) res[0][40]=a0;
  if (res[0]!=0) res[0][41]=a0;
  if (res[0]!=0) res[0][42]=a0;
  a5=-1.3803228073658729e+00;
  if (res[0]!=0) res[0][43]=a5;
  if (res[0]!=0) res[0][44]=a0;
  if (res[0]!=0) res[0][45]=a0;
  if (res[0]!=0) res[0][46]=a0;
  if (res[0]!=0) res[0][47]=a0;
  if (res[0]!=0) res[0][48]=a0;
  if (res[0]!=0) res[0][49]=a0;
  if (res[0]!=0) res[0][50]=a0;
  if (res[0]!=0) res[0][51]=a0;
  if (res[0]!=0) res[0][52]=a0;
  if (res[0]!=0) res[0][53]=a0;
  if (res[0]!=0) res[0][54]=a0;
  a5=cos(a3);
  a6=(a6*a5);
  a3=sin(a3);
  a2=(a2*a3);
  a6=(a6-a2);
  a6=(a6/a9);
  if (res[0]!=0) res[0][55]=a6;
  if (res[0]!=0) res[0][56]=a0;
  if (res[0]!=0) res[0][57]=a0;
  if (res[0]!=0) res[0][58]=a0;
  if (res[0]!=0) res[0][59]=a0;
  if (res[0]!=0) res[0][60]=a0;
  if (res[0]!=0) res[0][61]=a0;
  if (res[0]!=0) res[0][62]=a1;
  a7=(a7/a9);
  if (res[0]!=0) res[0][63]=a7;
  return 0;
}

void impl_jacFun_x_incref(void) {
}

void impl_jacFun_x_decref(void) {
}

int impl_jacFun_x_n_in(void) { return 3;}

int impl_jacFun_x_n_out(void) { return 1;}

const char* impl_jacFun_x_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  default: return 0;
  }
}

const char* impl_jacFun_x_name_out(int i){
  switch (i) {
  case 0: return "o0";
  default: return 0;
  }
}

const int* impl_jacFun_x_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s0;
  case 2: return s1;
  default: return 0;
  }
}

const int* impl_jacFun_x_sparsity_out(int i) {
  switch (i) {
  case 0: return s2;
  default: return 0;
  }
}

int impl_jacFun_x_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
