/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) jac_crane_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[6] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
#define s2 CASADI_PREFIX(s2)
/* jacFun */
int jacFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  real_t a1=4.7418203070092001e-02;
  real_t a2=arg[0] ? arg[0][4] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  a2=-7.8182378879940387e+01;
  a0=(a2*a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][2]=a0;
  real_t a3=3.4087337273385997e-02;
  real_t a4=arg[0] ? arg[0][5] : 0;
  a3=(a3*a4);
  a3=(a0-a3);
  a4=-4.0493711676434543e+01;
  a3=(a4*a3);
  if (res[0]!=0) res[0][3]=a3;
  a3=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][4]=a3;
  real_t a5=arg[1] ? arg[1][1] : 0;
  if (res[0]!=0) res[0][5]=a5;
  a5=arg[0] ? arg[0][7] : 0;
  if (res[0]!=0) res[0][6]=a5;
  a1=(a1*a3);
  a3=arg[0] ? arg[0][6] : 0;
  real_t a6=cos(a3);
  a6=(a1*a6);
  real_t a7=sin(a3);
  real_t a8=9.8100000000000005e+00;
  a7=(a8*a7);
  a6=(a6+a7);
  a7=2.;
  a0=(a7*a0);
  real_t a9=(a0*a5);
  a6=(a6+a9);
  a9=arg[0] ? arg[0][2] : 0;
  a6=(a6/a9);
  real_t a10=(-a6);
  if (res[0]!=0) res[0][7]=a10;
  a10=0.;
  if (res[1]!=0) res[1][0]=a10;
  if (res[1]!=0) res[1][1]=a10;
  if (res[1]!=0) res[1][2]=a10;
  if (res[1]!=0) res[1][3]=a10;
  if (res[1]!=0) res[1][4]=a10;
  if (res[1]!=0) res[1][5]=a10;
  if (res[1]!=0) res[1][6]=a10;
  if (res[1]!=0) res[1][7]=a10;
  real_t a11=1.;
  if (res[1]!=0) res[1][8]=a11;
  if (res[1]!=0) res[1][9]=a2;
  if (res[1]!=0) res[1][10]=a10;
  if (res[1]!=0) res[1][11]=a10;
  if (res[1]!=0) res[1][12]=a10;
  if (res[1]!=0) res[1][13]=a10;
  if (res[1]!=0) res[1][14]=a10;
  if (res[1]!=0) res[1][15]=a10;
  if (res[1]!=0) res[1][16]=a10;
  if (res[1]!=0) res[1][17]=a10;
  if (res[1]!=0) res[1][18]=a10;
  if (res[1]!=0) res[1][19]=a10;
  if (res[1]!=0) res[1][20]=a10;
  if (res[1]!=0) res[1][21]=a10;
  if (res[1]!=0) res[1][22]=a10;
  a6=(a6/a9);
  if (res[1]!=0) res[1][23]=a6;
  if (res[1]!=0) res[1][24]=a10;
  if (res[1]!=0) res[1][25]=a10;
  if (res[1]!=0) res[1][26]=a11;
  if (res[1]!=0) res[1][27]=a4;
  if (res[1]!=0) res[1][28]=a10;
  if (res[1]!=0) res[1][29]=a10;
  if (res[1]!=0) res[1][30]=a10;
  a7=(a7*a5);
  a7=(a7/a9);
  a7=(-a7);
  if (res[1]!=0) res[1][31]=a7;
  if (res[1]!=0) res[1][32]=a10;
  a7=3.7072679182318851e+00;
  if (res[1]!=0) res[1][33]=a7;
  if (res[1]!=0) res[1][34]=a10;
  if (res[1]!=0) res[1][35]=a10;
  if (res[1]!=0) res[1][36]=a10;
  if (res[1]!=0) res[1][37]=a10;
  if (res[1]!=0) res[1][38]=a10;
  if (res[1]!=0) res[1][39]=a10;
  if (res[1]!=0) res[1][40]=a10;
  if (res[1]!=0) res[1][41]=a10;
  if (res[1]!=0) res[1][42]=a10;
  a7=1.3803228073658729e+00;
  if (res[1]!=0) res[1][43]=a7;
  if (res[1]!=0) res[1][44]=a10;
  if (res[1]!=0) res[1][45]=a10;
  if (res[1]!=0) res[1][46]=a10;
  if (res[1]!=0) res[1][47]=a10;
  if (res[1]!=0) res[1][48]=a10;
  if (res[1]!=0) res[1][49]=a10;
  if (res[1]!=0) res[1][50]=a10;
  if (res[1]!=0) res[1][51]=a10;
  if (res[1]!=0) res[1][52]=a10;
  if (res[1]!=0) res[1][53]=a10;
  if (res[1]!=0) res[1][54]=a10;
  a7=cos(a3);
  a8=(a8*a7);
  a3=sin(a3);
  a1=(a1*a3);
  a8=(a8-a1);
  a8=(a8/a9);
  a8=(-a8);
  if (res[1]!=0) res[1][55]=a8;
  if (res[1]!=0) res[1][56]=a10;
  if (res[1]!=0) res[1][57]=a10;
  if (res[1]!=0) res[1][58]=a10;
  if (res[1]!=0) res[1][59]=a10;
  if (res[1]!=0) res[1][60]=a10;
  if (res[1]!=0) res[1][61]=a10;
  if (res[1]!=0) res[1][62]=a11;
  a0=(a0/a9);
  a0=(-a0);
  if (res[1]!=0) res[1][63]=a0;
  return 0;
}

void jacFun_incref(void) {
}

void jacFun_decref(void) {
}

int jacFun_n_in(void) { return 2;}

int jacFun_n_out(void) { return 2;}

const char* jacFun_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  default: return 0;
  }
}

const char* jacFun_name_out(int i){
  switch (i) {
  case 0: return "o0";
  case 1: return "o1";
  default: return 0;
  }
}

const int* jacFun_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s1;
  default: return 0;
  }
}

const int* jacFun_sparsity_out(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s2;
  default: return 0;
  }
}

int jacFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 12;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
