/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) vde_forw_model_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[21] = {8, 2, 0, 8, 16, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[6] = {2, 1, 0, 2, 0, 1};
#define s3 CASADI_PREFIX(s3)
/* vdeFun */
int vdeFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  real_t a1=4.7418203070092001e-02;
  real_t a2=arg[0] ? arg[0][4] : 0;
  a2=(a1*a2);
  a0=(a0-a2);
  a2=-7.8182378879940387e+01;
  a0=(a2*a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][2]=a0;
  real_t a3=3.4087337273385997e-02;
  real_t a4=arg[0] ? arg[0][5] : 0;
  a4=(a3*a4);
  a4=(a0-a4);
  real_t a5=-4.0493711676434543e+01;
  a4=(a5*a4);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[3] ? arg[3][0] : 0;
  if (res[0]!=0) res[0][4]=a4;
  real_t a6=arg[3] ? arg[3][1] : 0;
  if (res[0]!=0) res[0][5]=a6;
  a6=arg[0] ? arg[0][7] : 0;
  if (res[0]!=0) res[0][6]=a6;
  a4=(a1*a4);
  real_t a7=arg[0] ? arg[0][6] : 0;
  real_t a8=cos(a7);
  real_t a9=(a4*a8);
  real_t a10=sin(a7);
  real_t a11=9.8100000000000005e+00;
  a10=(a11*a10);
  a9=(a9+a10);
  a10=2.;
  a0=(a10*a0);
  real_t a12=(a0*a6);
  a9=(a9+a12);
  a12=arg[0] ? arg[0][2] : 0;
  a9=(a9/a12);
  real_t a13=(-a9);
  if (res[0]!=0) res[0][7]=a13;
  a13=arg[1] ? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a13;
  real_t a14=arg[1] ? arg[1][4] : 0;
  a14=(a1*a14);
  a13=(a13-a14);
  a13=(a2*a13);
  if (res[1]!=0) res[1][1]=a13;
  a13=arg[1] ? arg[1][3] : 0;
  if (res[1]!=0) res[1][2]=a13;
  a14=arg[1] ? arg[1][5] : 0;
  a14=(a3*a14);
  a14=(a13-a14);
  a14=(a5*a14);
  if (res[1]!=0) res[1][3]=a14;
  a14=0.;
  if (res[1]!=0) res[1][4]=a14;
  if (res[1]!=0) res[1][5]=a14;
  real_t a15=arg[1] ? arg[1][7] : 0;
  if (res[1]!=0) res[1][6]=a15;
  real_t a16=cos(a7);
  real_t a17=arg[1] ? arg[1][6] : 0;
  real_t a18=(a16*a17);
  a18=(a11*a18);
  real_t a19=sin(a7);
  a17=(a19*a17);
  a17=(a4*a17);
  a18=(a18-a17);
  a13=(a10*a13);
  a13=(a6*a13);
  a15=(a0*a15);
  a13=(a13+a15);
  a18=(a18+a13);
  a18=(a18/a12);
  a13=(a9/a12);
  a15=arg[1] ? arg[1][2] : 0;
  a15=(a13*a15);
  a18=(a18-a15);
  a18=(-a18);
  if (res[1]!=0) res[1][7]=a18;
  a18=arg[1] ? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a18;
  a15=arg[1] ? arg[1][12] : 0;
  a15=(a1*a15);
  a18=(a18-a15);
  a18=(a2*a18);
  if (res[1]!=0) res[1][9]=a18;
  a18=arg[1] ? arg[1][11] : 0;
  if (res[1]!=0) res[1][10]=a18;
  a15=arg[1] ? arg[1][13] : 0;
  a15=(a3*a15);
  a15=(a18-a15);
  a15=(a5*a15);
  if (res[1]!=0) res[1][11]=a15;
  if (res[1]!=0) res[1][12]=a14;
  if (res[1]!=0) res[1][13]=a14;
  a15=arg[1] ? arg[1][15] : 0;
  if (res[1]!=0) res[1][14]=a15;
  a17=arg[1] ? arg[1][14] : 0;
  real_t a20=(a16*a17);
  a20=(a11*a20);
  a17=(a19*a17);
  a17=(a4*a17);
  a20=(a20-a17);
  a18=(a10*a18);
  a18=(a6*a18);
  a15=(a0*a15);
  a18=(a18+a15);
  a20=(a20+a18);
  a20=(a20/a12);
  a18=arg[1] ? arg[1][10] : 0;
  a18=(a13*a18);
  a20=(a20-a18);
  a20=(-a20);
  if (res[1]!=0) res[1][15]=a20;
  a20=arg[1] ? arg[1][17] : 0;
  if (res[1]!=0) res[1][16]=a20;
  a18=arg[1] ? arg[1][20] : 0;
  a18=(a1*a18);
  a20=(a20-a18);
  a20=(a2*a20);
  if (res[1]!=0) res[1][17]=a20;
  a20=arg[1] ? arg[1][19] : 0;
  if (res[1]!=0) res[1][18]=a20;
  a18=arg[1] ? arg[1][21] : 0;
  a18=(a3*a18);
  a18=(a20-a18);
  a18=(a5*a18);
  if (res[1]!=0) res[1][19]=a18;
  if (res[1]!=0) res[1][20]=a14;
  if (res[1]!=0) res[1][21]=a14;
  a18=arg[1] ? arg[1][23] : 0;
  if (res[1]!=0) res[1][22]=a18;
  a15=arg[1] ? arg[1][22] : 0;
  a17=(a16*a15);
  a17=(a11*a17);
  a15=(a19*a15);
  a15=(a4*a15);
  a17=(a17-a15);
  a20=(a10*a20);
  a20=(a6*a20);
  a18=(a0*a18);
  a20=(a20+a18);
  a17=(a17+a20);
  a17=(a17/a12);
  a20=arg[1] ? arg[1][18] : 0;
  a20=(a13*a20);
  a17=(a17-a20);
  a17=(-a17);
  if (res[1]!=0) res[1][23]=a17;
  a17=arg[1] ? arg[1][25] : 0;
  if (res[1]!=0) res[1][24]=a17;
  a20=arg[1] ? arg[1][28] : 0;
  a20=(a1*a20);
  a17=(a17-a20);
  a17=(a2*a17);
  if (res[1]!=0) res[1][25]=a17;
  a17=arg[1] ? arg[1][27] : 0;
  if (res[1]!=0) res[1][26]=a17;
  a20=arg[1] ? arg[1][29] : 0;
  a20=(a3*a20);
  a20=(a17-a20);
  a20=(a5*a20);
  if (res[1]!=0) res[1][27]=a20;
  if (res[1]!=0) res[1][28]=a14;
  if (res[1]!=0) res[1][29]=a14;
  a20=arg[1] ? arg[1][31] : 0;
  if (res[1]!=0) res[1][30]=a20;
  a18=arg[1] ? arg[1][30] : 0;
  a15=(a16*a18);
  a15=(a11*a15);
  a18=(a19*a18);
  a18=(a4*a18);
  a15=(a15-a18);
  a17=(a10*a17);
  a17=(a6*a17);
  a20=(a0*a20);
  a17=(a17+a20);
  a15=(a15+a17);
  a15=(a15/a12);
  a17=arg[1] ? arg[1][26] : 0;
  a17=(a13*a17);
  a15=(a15-a17);
  a15=(-a15);
  if (res[1]!=0) res[1][31]=a15;
  a15=arg[1] ? arg[1][33] : 0;
  if (res[1]!=0) res[1][32]=a15;
  a17=arg[1] ? arg[1][36] : 0;
  a17=(a1*a17);
  a15=(a15-a17);
  a15=(a2*a15);
  if (res[1]!=0) res[1][33]=a15;
  a15=arg[1] ? arg[1][35] : 0;
  if (res[1]!=0) res[1][34]=a15;
  a17=arg[1] ? arg[1][37] : 0;
  a17=(a3*a17);
  a17=(a15-a17);
  a17=(a5*a17);
  if (res[1]!=0) res[1][35]=a17;
  if (res[1]!=0) res[1][36]=a14;
  if (res[1]!=0) res[1][37]=a14;
  a17=arg[1] ? arg[1][39] : 0;
  if (res[1]!=0) res[1][38]=a17;
  a20=arg[1] ? arg[1][38] : 0;
  a18=(a16*a20);
  a18=(a11*a18);
  a20=(a19*a20);
  a20=(a4*a20);
  a18=(a18-a20);
  a15=(a10*a15);
  a15=(a6*a15);
  a17=(a0*a17);
  a15=(a15+a17);
  a18=(a18+a15);
  a18=(a18/a12);
  a15=arg[1] ? arg[1][34] : 0;
  a15=(a13*a15);
  a18=(a18-a15);
  a18=(-a18);
  if (res[1]!=0) res[1][39]=a18;
  a18=arg[1] ? arg[1][41] : 0;
  if (res[1]!=0) res[1][40]=a18;
  a15=arg[1] ? arg[1][44] : 0;
  a15=(a1*a15);
  a18=(a18-a15);
  a18=(a2*a18);
  if (res[1]!=0) res[1][41]=a18;
  a18=arg[1] ? arg[1][43] : 0;
  if (res[1]!=0) res[1][42]=a18;
  a15=arg[1] ? arg[1][45] : 0;
  a15=(a3*a15);
  a15=(a18-a15);
  a15=(a5*a15);
  if (res[1]!=0) res[1][43]=a15;
  if (res[1]!=0) res[1][44]=a14;
  if (res[1]!=0) res[1][45]=a14;
  a15=arg[1] ? arg[1][47] : 0;
  if (res[1]!=0) res[1][46]=a15;
  a17=arg[1] ? arg[1][46] : 0;
  a20=(a16*a17);
  a20=(a11*a20);
  a17=(a19*a17);
  a17=(a4*a17);
  a20=(a20-a17);
  a18=(a10*a18);
  a18=(a6*a18);
  a15=(a0*a15);
  a18=(a18+a15);
  a20=(a20+a18);
  a20=(a20/a12);
  a18=arg[1] ? arg[1][42] : 0;
  a18=(a13*a18);
  a20=(a20-a18);
  a20=(-a20);
  if (res[1]!=0) res[1][47]=a20;
  a20=arg[1] ? arg[1][49] : 0;
  if (res[1]!=0) res[1][48]=a20;
  a18=arg[1] ? arg[1][52] : 0;
  a18=(a1*a18);
  a20=(a20-a18);
  a20=(a2*a20);
  if (res[1]!=0) res[1][49]=a20;
  a20=arg[1] ? arg[1][51] : 0;
  if (res[1]!=0) res[1][50]=a20;
  a18=arg[1] ? arg[1][53] : 0;
  a18=(a3*a18);
  a18=(a20-a18);
  a18=(a5*a18);
  if (res[1]!=0) res[1][51]=a18;
  if (res[1]!=0) res[1][52]=a14;
  if (res[1]!=0) res[1][53]=a14;
  a18=arg[1] ? arg[1][55] : 0;
  if (res[1]!=0) res[1][54]=a18;
  a15=arg[1] ? arg[1][54] : 0;
  a17=(a16*a15);
  a17=(a11*a17);
  a15=(a19*a15);
  a15=(a4*a15);
  a17=(a17-a15);
  a20=(a10*a20);
  a20=(a6*a20);
  a18=(a0*a18);
  a20=(a20+a18);
  a17=(a17+a20);
  a17=(a17/a12);
  a20=arg[1] ? arg[1][50] : 0;
  a20=(a13*a20);
  a17=(a17-a20);
  a17=(-a17);
  if (res[1]!=0) res[1][55]=a17;
  a17=arg[1] ? arg[1][57] : 0;
  if (res[1]!=0) res[1][56]=a17;
  a20=arg[1] ? arg[1][60] : 0;
  a20=(a1*a20);
  a17=(a17-a20);
  a17=(a2*a17);
  if (res[1]!=0) res[1][57]=a17;
  a17=arg[1] ? arg[1][59] : 0;
  if (res[1]!=0) res[1][58]=a17;
  a20=arg[1] ? arg[1][61] : 0;
  a20=(a3*a20);
  a20=(a17-a20);
  a20=(a5*a20);
  if (res[1]!=0) res[1][59]=a20;
  if (res[1]!=0) res[1][60]=a14;
  if (res[1]!=0) res[1][61]=a14;
  a20=arg[1] ? arg[1][63] : 0;
  if (res[1]!=0) res[1][62]=a20;
  a18=arg[1] ? arg[1][62] : 0;
  a16=(a16*a18);
  a16=(a11*a16);
  a19=(a19*a18);
  a19=(a4*a19);
  a16=(a16-a19);
  a17=(a10*a17);
  a17=(a6*a17);
  a20=(a0*a20);
  a17=(a17+a20);
  a16=(a16+a17);
  a16=(a16/a12);
  a17=arg[1] ? arg[1][58] : 0;
  a13=(a13*a17);
  a16=(a16-a13);
  a16=(-a16);
  if (res[1]!=0) res[1][63]=a16;
  a16=arg[2] ? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a16;
  a13=arg[2] ? arg[2][4] : 0;
  a13=(a1*a13);
  a16=(a16-a13);
  a16=(a2*a16);
  if (res[2]!=0) res[2][1]=a16;
  a16=arg[2] ? arg[2][3] : 0;
  if (res[2]!=0) res[2][2]=a16;
  a13=arg[2] ? arg[2][5] : 0;
  a13=(a3*a13);
  a13=(a16-a13);
  a13=(a5*a13);
  if (res[2]!=0) res[2][3]=a13;
  a13=1.;
  if (res[2]!=0) res[2][4]=a13;
  if (res[2]!=0) res[2][5]=a14;
  a17=arg[2] ? arg[2][7] : 0;
  if (res[2]!=0) res[2][6]=a17;
  a8=(a1*a8);
  a8=(a8/a12);
  a20=cos(a7);
  a19=arg[2] ? arg[2][6] : 0;
  a18=(a20*a19);
  a18=(a11*a18);
  a7=sin(a7);
  a19=(a7*a19);
  a19=(a4*a19);
  a18=(a18-a19);
  a16=(a10*a16);
  a16=(a6*a16);
  a17=(a0*a17);
  a16=(a16+a17);
  a18=(a18+a16);
  a18=(a18/a12);
  a9=(a9/a12);
  a16=arg[2] ? arg[2][2] : 0;
  a16=(a9*a16);
  a18=(a18-a16);
  a8=(a8+a18);
  a8=(-a8);
  if (res[2]!=0) res[2][7]=a8;
  a8=arg[2] ? arg[2][9] : 0;
  if (res[2]!=0) res[2][8]=a8;
  a18=arg[2] ? arg[2][12] : 0;
  a1=(a1*a18);
  a8=(a8-a1);
  a2=(a2*a8);
  if (res[2]!=0) res[2][9]=a2;
  a2=arg[2] ? arg[2][11] : 0;
  if (res[2]!=0) res[2][10]=a2;
  a8=arg[2] ? arg[2][13] : 0;
  a3=(a3*a8);
  a3=(a2-a3);
  a5=(a5*a3);
  if (res[2]!=0) res[2][11]=a5;
  if (res[2]!=0) res[2][12]=a14;
  if (res[2]!=0) res[2][13]=a13;
  a13=arg[2] ? arg[2][15] : 0;
  if (res[2]!=0) res[2][14]=a13;
  a14=arg[2] ? arg[2][14] : 0;
  a20=(a20*a14);
  a11=(a11*a20);
  a7=(a7*a14);
  a4=(a4*a7);
  a11=(a11-a4);
  a10=(a10*a2);
  a6=(a6*a10);
  a0=(a0*a13);
  a6=(a6+a0);
  a11=(a11+a6);
  a11=(a11/a12);
  a12=arg[2] ? arg[2][10] : 0;
  a9=(a9*a12);
  a11=(a11-a9);
  a11=(-a11);
  if (res[2]!=0) res[2][15]=a11;
  return 0;
}

void vdeFun_incref(void) {
}

void vdeFun_decref(void) {
}

int vdeFun_n_in(void) { return 4;}

int vdeFun_n_out(void) { return 3;}

const char* vdeFun_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  case 3: return "i3";
  default: return 0;
  }
}

const char* vdeFun_name_out(int i){
  switch (i) {
  case 0: return "o0";
  case 1: return "o1";
  case 2: return "o2";
  default: return 0;
  }
}

const int* vdeFun_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s1;
  case 2: return s2;
  case 3: return s3;
  default: return 0;
  }
}

const int* vdeFun_sparsity_out(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s1;
  case 2: return s2;
  default: return 0;
  }
}

int vdeFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 21;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
